<?php

namespace App;

//use App\Scopes\TenantModels;
use App\Scopes\TenantGlobalScope;
use App\Scopes\TenantScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //use TenantModels;
    use TenantGlobalScope;

    protected $fillable = [
        'name'
    ];


    //adicionando scopo global - foi para trait
    /*protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new TenantScope());
    }*/

    //Escopo Local
    /*public function scopeByAccount(Builder $query, $accountId){
        return $query->where('account_id',$accountId);
    }*/
}