<?php
/**
 * Created by PhpStorm.
 * User: josuecamelo
 * Date: 15/12/17
 * Time: 14:11
 */

namespace App\Scopes;

use Illuminate\Database\Eloquent\Model;

trait TenantModels{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new TenantScope());

        //Ao Criar Registro
        static::creating(function(Model $model){
            $accountId = \Auth::user()->account_id;
            $model->account_id = $accountId;
        });
    }
}