<?php
/**
 * Created by PhpStorm.
 * User: josuecamelo
 * Date: 15/12/17
 * Time: 14:11
 */

namespace App\Scopes;

use App\Tenant\TenantManager;
use Illuminate\Database\Eloquent\Model;

trait TenantModels{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new TenantScope());

        //Ao Criar Registro
        static::creating(function(Model $model){
            /*if(\Auth::user()){
                $accountId = \Auth::user()->account_id;
                $model->account_id = $accountId;
            }*/

            /** @var TenantManager $tenantManager */
            $tenantManager = app(TenantManager::class);
            if($tenantManager->getTenant()){
                $accountId = $tenantManager->getTenant()->id;
                $model->account_id = $accountId;
            }
        });
    }
}