<?php
/**
 * Created by PhpStorm.
 * User: josuecamelo
 * Date: 15/12/17
 * Time: 14:11
 */

namespace App\Scopes;

trait TenantGlobalScope{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new TenantScope());
    }
}